server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=destinations&reWriteBatchedInserts=true
    username: postgres
    password:
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 5000
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    repeatable-sql-migration-prefix: R